# Site settings
title: LouisiANIME
email: admin@louisianime.com
description: "LouisiANIME is a 3 day anime convention on May 15-17, 2015 in Lafayette,LA. Enjoy celebrity guests, extravagant costumes, arts, crafts, music, and dancing."
baseurl: ""
url: "http://www.louisianime.com"
twitter_username: LouisiANIME
facebook_username: LouisiANIME



# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
encoding: utf-8

paginate: 9
paginate_path: "/blog/page:num/"