# Site settings
title: LouisiANIME
email: admin@louisianime.com
description: "LouisiANIME is a 3 day anime convention is an event on March 25-27, 2016 in Baton Rouge, LA. Enjoy celebrity guests, extravagant costumes, arts, crafts, music, and dancing!"
baseurl: ""
url: "http://www.louisianime.com"
twitter_username: LouisiANIME
facebook_username: LouisiANIME



# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
encoding: utf-8
categories: [information, guests_2015, guests_2016, guests_2017, cosplay_guests_2016]

paginate: 9
paginate_path: "/blog/page:num/"

# Includes and Excludes
include: [.htaccess]

#Gems
gems: [jekyll-paginate]
